language: node_js
node_js:
  - "6.1"

install:
  - npm install
  - docker pull lukasmartinelli/hadolint
  - cp conf/conf.example.js conf/conf.js

services:
  - docker

script:
  - docker run --rm -i lukasmartinelli/hadolint < Dockerfile
